"""empty message

Revision ID: 64a66e856c44
Revises: 3af86288590f
Create Date: 2017-02-01 07:45:21.948106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a66e856c44'
down_revision = '3af86288590f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('token', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
